# Generated by Django 6.0.7 on 2026-07-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم لوحة المعلومات')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_public', models.BooleanField(default=False, verbose_name='لوحة عامة')),
                ('is_default', models.BooleanField(default=False, verbose_name='اللوحة الافتراضية')),
                ('layout_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات التصميم')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='مرشحات اللوحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='صاحب لوحة المعلومات')),
            ],
            options={
                'verbose_name': 'لوحة معلومات',
                'verbose_name_plural': 'لوحات المعلومات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'عرض فقط'), ('edit', 'عرض وتعديل')], default='view', max_length=10, verbose_name='الصلاحية')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاركة')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='dashboards.dashboard', verbose_name='لوحة المعلومات')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='مشاركة مع')),
            ],
            options={
                'verbose_name': 'مشاركة لوحة',
                'verbose_name_plural': 'مشاركات اللوحات',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العنصر')),
                ('widget_type', models.CharField(choices=[('metric', 'بطاقة رقمية'), ('table', 'جدول'), ('bar', 'مخطط أعمدة'), ('line', 'مخطط خطي'), ('pie', 'مخطط دائري'), ('area', 'مخطط مساحي'), ('scatter', 'مخطط انتشار'), ('histogram', 'مدرج تكراري'), ('heatmap', 'خريطة حرارية'), ('text', 'نص')], max_length=30, verbose_name='نوع العنصر')),
                ('x_column', models.CharField(blank=True, max_length=255, verbose_name='عمود المحور الأفقي')),
                ('y_column', models.CharField(blank=True, max_length=255, verbose_name='عمود المحور الرأسي')),
                ('aggregation', models.CharField(blank=True, max_length=50, verbose_name='طريقة التجميع')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='الموقع الأفقي')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='الموقع الرأسي')),
                ('width', models.PositiveIntegerField(default=6, verbose_name='العرض')),
                ('height', models.PositiveIntegerField(default=4, verbose_name='الارتفاع')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات العنصر')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('analysis_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_widgets', to='analysis.analysisresult', verbose_name='نتيجة التحليل')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard', verbose_name='لوحة المعلومات')),
            ],
            options={
                'verbose_name': 'عنصر لوحة معلومات',
                'verbose_name_plural': 'عناصر لوحات المعلومات',
                'ordering': ['display_order', 'position_y', 'position_x'],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['owner', 'is_public'], name='dashboards__owner_i_3d3005_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardshare',
            constraint=models.UniqueConstraint(fields=('dashboard', 'shared_with'), name='unique_dashboard_share_per_user'),
        ),
    ]
