# Generated by Django 6.0.7 on 2026-07-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'فرد'), ('analyst', 'محلل بيانات'), ('company', 'شركة'), ('manager', 'مدير مؤسسة')], default='individual', max_length=20, verbose_name='نوع الحساب')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة أو المؤسسة')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='accounts/profile_images/', verbose_name='الصورة الشخصية')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى لحجم الملف بالميجابايت')),
                ('monthly_analysis_limit', models.PositiveIntegerField(default=20, verbose_name='الحد الشهري لعمليات التحليل')),
                ('analyses_used_this_month', models.PositiveIntegerField(default=0, verbose_name='التحليلات المستخدمة هذا الشهر')),
                ('is_verified', models.BooleanField(default=False, verbose_name='الحساب موثق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الملف الشخصي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
