# Generated by Django 6.0.7 on 2026-07-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('analysis', 'تقرير تحليل بيانات'), ('data_quality', 'تقرير جودة البيانات'), ('sales', 'تقرير مبيعات'), ('financial', 'تقرير مالي'), ('comparison', 'تقرير مقارنة'), ('executive', 'تقرير تنفيذي'), ('cleaned_data', 'ملف بيانات منظف')], default='analysis', max_length=30, verbose_name='نوع التقرير')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel XLSX'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='صيغة التقرير')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('queued', 'في قائمة الانتظار'), ('generating', 'جارٍ الإنشاء'), ('completed', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='new', max_length=20, verbose_name='حالة التقرير')),
                ('include_summary', models.BooleanField(default=True, verbose_name='تضمين الملخص')),
                ('include_tables', models.BooleanField(default=True, verbose_name='تضمين الجداول')),
                ('include_charts', models.BooleanField(default=True, verbose_name='تضمين الرسوم البيانية')),
                ('report_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات التقرير')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اكتمال التقرير')),
                ('analysis_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='analysis.analysisresult', verbose_name='نتيجة التحليل')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dashboards.dashboard', verbose_name='لوحة المعلومات')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='صاحب التقرير')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/generated/%Y/%m/', verbose_name='ملف التقرير')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف بالبايت')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات التحميل')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الملف')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'ملف تقرير',
                'verbose_name_plural': 'ملفات التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['owner', 'status'], name='reports_rep_owner_i_4e5b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
    ]
