# Generated by Django 6.0.7 on 2026-07-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التحليل')),
                ('analysis_type', models.CharField(choices=[('descriptive', 'تحليل وصفي'), ('data_quality', 'تحليل جودة البيانات'), ('sales', 'تحليل المبيعات'), ('financial', 'تحليل مالي'), ('correlation', 'تحليل الارتباط'), ('comparison', 'تحليل المقارنة'), ('custom', 'تحليل مخصص')], default='descriptive', max_length=30, verbose_name='نوع التحليل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('queued', 'في قائمة الانتظار'), ('processing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], db_index=True, default='new', max_length=20, verbose_name='حالة التحليل')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='قيمة من 0 إلى 100', verbose_name='نسبة التقدم')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء التنفيذ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت اكتمال التنفيذ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='datasets.dataset', verbose_name='ملف البيانات')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='صاحب التحليل')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='datasets.datasetsheet', verbose_name='ورقة العمل')),
            ],
            options={
                'verbose_name': 'عملية تحليل',
                'verbose_name_plural': 'عمليات التحليل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_columns', models.JSONField(blank=True, default=list, verbose_name='الأعمدة المحددة')),
                ('group_by_columns', models.JSONField(blank=True, default=list, verbose_name='أعمدة التجميع')),
                ('value_columns', models.JSONField(blank=True, default=list, verbose_name='أعمدة القيم')),
                ('date_column', models.CharField(blank=True, max_length=255, verbose_name='عمود التاريخ')),
                ('missing_values_method', models.CharField(choices=[('none', 'دون تغيير'), ('drop_rows', 'حذف الصفوف الفارغة'), ('drop_columns', 'حذف الأعمدة الفارغة'), ('fill_zero', 'التعبئة بالصفر'), ('fill_mean', 'التعبئة بالمتوسط'), ('fill_median', 'التعبئة بالوسيط'), ('fill_mode', 'التعبئة بالقيمة الأكثر تكرارًا'), ('custom', 'قيمة مخصصة')], default='none', max_length=30, verbose_name='طريقة معالجة القيم الفارغة')),
                ('custom_fill_value', models.CharField(blank=True, max_length=255, verbose_name='قيمة التعبئة المخصصة')),
                ('remove_duplicates', models.BooleanField(default=False, verbose_name='حذف الصفوف المكررة')),
                ('remove_outliers', models.BooleanField(default=False, verbose_name='إزالة القيم الشاذة')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='المرشحات')),
                ('sorting', models.JSONField(blank=True, default=list, verbose_name='إعدادات الترتيب')),
                ('additional_options', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الإعدادات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ تحديث الإعدادات')),
                ('analysis_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='analysis.analysisjob', verbose_name='عملية التحليل')),
            ],
            options={
                'verbose_name': 'إعدادات التحليل',
                'verbose_name_plural': 'إعدادات التحليلات',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص النتائج')),
                ('statistics', models.JSONField(blank=True, default=dict, verbose_name='النتائج الإحصائية')),
                ('table_data', models.JSONField(blank=True, default=list, verbose_name='بيانات الجدول')),
                ('chart_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الرسوم البيانية')),
                ('insights', models.JSONField(blank=True, default=list, verbose_name='الاستنتاجات')),
                ('rows_before_cleaning', models.PositiveBigIntegerField(default=0, verbose_name='عدد الصفوف قبل التنظيف')),
                ('rows_after_cleaning', models.PositiveBigIntegerField(default=0, verbose_name='عدد الصفوف بعد التنظيف')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='analysis/processed/%Y/%m/', verbose_name='الملف المعالج')),
                ('execution_time_seconds', models.FloatField(default=0, verbose_name='مدة التنفيذ بالثواني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ حفظ النتيجة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ تحديث النتيجة')),
                ('analysis_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisjob', verbose_name='عملية التحليل')),
            ],
            options={
                'verbose_name': 'نتيجة تحليل',
                'verbose_name_plural': 'نتائج التحليلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCleaningOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('drop_missing', 'حذف القيم الفارغة'), ('fill_missing', 'تعبئة القيم الفارغة'), ('remove_duplicates', 'حذف التكرارات'), ('rename_column', 'إعادة تسمية عمود'), ('drop_column', 'حذف عمود'), ('replace_value', 'استبدال قيمة'), ('change_type', 'تغيير نوع البيانات'), ('format_date', 'تنسيق التاريخ'), ('remove_outliers', 'إزالة القيم الشاذة'), ('trim_text', 'تنظيف النصوص')], max_length=30, verbose_name='نوع عملية التنظيف')),
                ('column_name', models.CharField(blank=True, max_length=255, verbose_name='اسم العمود')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='معاملات العملية')),
                ('operation_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب التنفيذ')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_operations', to='analysis.analysisjob', verbose_name='عملية التحليل')),
            ],
            options={
                'verbose_name': 'عملية تنظيف',
                'verbose_name_plural': 'عمليات تنظيف البيانات',
                'ordering': ['operation_order'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['owner', 'status'], name='analysis_an_owner_i_c0f1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['analysis_type'], name='analysis_an_analysi_518bb1_idx'),
        ),
    ]
